title: Steve Honey
description: A collection of notes to myself that might help others.
author: Steve Honey
github: https://github.com/stevenhoney
about: A collection of notes to myself that might help others.
disqus_shortname:
google_analytics:

enableTags: true
tagarray: []

collections:
  project:  
    output: true
    permaalt-text: /project/:path/

social: 
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/steve-honey-9957924a/"
    - icon: fa-github
      link: "https://github.com/stevenhoney"
    - icon: fa-wordpress
      link: "https://profiles.wordpress.org/stevehoneynz/"

native: 
    - icon: fa-shopify
      alt-text: Liquid / Shopify API
    - icon: fa-js
      alt-text: Javascript
    - icon: fa-css
      alt-text: SCSS

fluent: 
    - icon: fa-linkedin
      alt-text: "https://www.linkedin.com/in/steve-honey-9957924a/"
    - icon: fa-github
      alt-text: "https://github.com/stevenhoney"
    - icon: fa-wordpress
      alt-text: "https://profiles.wordpress.org/stevehoneynz/"

conversational: 
    - icon: fa-linkedin
      alt-text: "https://www.linkedin.com/in/steve-honey-9957924a/"
    - icon: fa-github
      alt-text: "https://github.com/stevenhoney"
    - icon: fa-wordpress
      alt-text: "https://profiles.wordpress.org/stevehoneynz/"

share:
  twitter_username:
  fb_appid:

urls:
    - text: About
      url: /about/
    - text: Contact
      url: /contact/

url: "https://stevenhoney.github.io"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
