title: Steve Honey - Full stack developer | Ecommerce Specialist
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stevenhoney.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Steve Honey # add your name
author-img: profile.webp # add your photo
about-author: Experienced in front-end web dev, intergation projects, multiple ecomm, CMS and ERP platforms. # add description
social-twitter:  # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: stevenhoney # add your Github handle
social-linkedin: steve-honey-9957924a # add your Linkedin handle
social-wordpress: stevehoneynz
social-email: # add your Email address

# Languages/Platforms
languages-1: 
    - icon: fa-shopify
      alt-text: "Liquid / Shopify APIs"
    - icon: netsuite-icon
      alt-text: "Netsuite: SuiteScript 2.0, SCA, Super Admin"
    - icon: fa-js
      alt-text: "Javascript"
    - icon: fa-sass
      alt-text: "SCSS"
    - icon: fa-wordpress-simple
      alt-text: "WordPress: Core contributor, custom themes, plugins, multisite"

languages-2:
    - icon: celigo-icon
      alt-text: "Celigo"
    - icon: fa-magento
      alt-text: "Magento"
    - icon: fa-php
      alt-text: "PHP"
    - icon: sql-icon
      alt-text: "SQL / MySQL / PostgreSQL"
    - icon: power-bi-icon
      alt-text: "Power BI / DAX"
    - icon: fa-jira
      alt-text: "Jira / Atlassian"
    - icon: fa-git-alt
      alt-text: "Git"
    - icon: fa-bitbucket
      alt-text: "Bitbucket"
    - icon: fa-gulp
      alt-text: "Gulp"
    - icon: "devicon-webpack-plain devicon"
      alt-text: "Webpack"
    - icon: "devicon-grunt-plain devicon"
      alt-text: "Grunt"
    - icon: "devicon-bower-plain devicon"
      alt-text: "Bower"
    - icon: "devicon-handlebars-plain devicon"
      alt-text: "Handlebars"
    - icon: "devicon-bootstrap-plain devicon"
      alt-text: "Bootstrap"
    - icon: "devicon-foundation-plain devicon"
      alt-text: "Foundation"
    - icon: "fa-algolia"
      alt-text: "Algolia"
    - icon: "fa-dropbox"
      alt-text: "Dropbox API"
    - icon: "devicon-photoshop-plain devicon"
      alt-text: "Photoshop"
    - icon: "fa-slack"
      alt-text: "Slack"
    - icon: "fa-microsoft"
      alt-text: "Microsoft: Sharepoint/Teams/o365 Admin"

# Disqus
discus-identifier: stevehoney # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 99
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
